#include "SDL2/SDL.h"

#define KEY_W 				SDL_SCANCODE_W
#define KEY_A 				SDL_SCANCODE_A
#define KEY_S 				SDL_SCANCODE_S
#define KEY_D 				SDL_SCANCODE_D
#define KEY_SHIFT_LEFT 		SDL_SCANCODE_LSHIFT

#define KEY_ARROW_LEFT 		SDL_SCANCODE_LEFT
#define KEY_ARROW_RIGHT 	SDL_SCANCODE_RIGHT
#define KEY_ARROW_UP 		SDL_SCANCODE_UP
#define KEY_ARROW_DOWN 		SDL_SCANCODE_DOWN
#define KEY_RIGHT_ZERO 		SDL_SCANCODE_RCTRL

#define KEY_ESC 			SDL_SCANCODE_ESCAPE
#define KEY_RETURN 			SDL_SCANCODE_RETURN
#define KEY_SPACE_BAR 		41
#define KEY_BACKSPACE 		102

#define KEY_CONTROL 		20

// Pushbutton keys
#define KEY1 				SDL_SCANCODE_DOWN
#define KEY2  				SDL_SCANCODE_UP
#define KEY3 				SDL_SCANCODE_RETURN
